vim.keymap.set('n', '<leader>pi', ':PlugInstall<CR>', {noremap = true})
vim.keymap.set('n', '<leader>so', ':source %<CR>', {noremap = true})
vim.keymap.set('n', '<leader>f', ':Files<CR>', {noremap = true})
vim.keymap.set('n', '<leader>c', ':Commentary<CR>', {noremap = true})
vim.keymap.set('n', '<leader>vrc', ':e ~/.config/nvim/init.vim<CR>', {noremap = true})
vim.keymap.set('n', '<leader>swa', '<Plug>GenerateDiagram', {noremap = true})
